// Objective-C API for talking to swiftV2ray.com/tun2socks Go package.
//   gobind -lang=objc swiftV2ray.com/tun2socks
//
// File is generated by gobind. Do not edit.

#ifndef __Tun2socks_H__
#define __Tun2socks_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Tun2socksPacketFlow;
@class Tun2socksPacketFlow;

@protocol Tun2socksPacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

FOUNDATION_EXPORT void Tun2socksInputPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void Tun2socksStartV2Ray(id<Tun2socksPacketFlow> _Nullable packetFlow, NSData* _Nullable configBytes);

@class Tun2socksPacketFlow;

@interface Tun2socksPacketFlow : NSObject <goSeqRefInterface, Tun2socksPacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
