// Objective-C API for talking to github.com/eycorsican/go-tun2socks-mobile Go package.
//   gobind -lang=objc github.com/eycorsican/go-tun2socks-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Tun2socks_H__
#define __Tun2socks_H__

@import Foundation;
#include "Universe.objc.h"


@protocol Tun2socksPacketFlow;
@class Tun2socksPacketFlow;

@protocol Tun2socksPacketFlow <NSObject>
- (void)writePacket:(NSData*)packet;
@end

FOUNDATION_EXPORT void Tun2socksInputPacket(NSData* data);

FOUNDATION_EXPORT void Tun2socksStartShadowsocks(id<Tun2socksPacketFlow> packetFlow, NSString* proxyHost, long proxyPort, NSString* proxyCipher, NSString* proxyPassword);

FOUNDATION_EXPORT void Tun2socksStartV2Ray(id<Tun2socksPacketFlow> packetFlow, NSData* configBytes);

@class Tun2socksPacketFlow;

@interface Tun2socksPacketFlow : NSObject <goSeqRefInterface, Tun2socksPacketFlow> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)writePacket:(NSData*)packet;
@end

#endif
